# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        egomotion: 5
        monocular depth: 4
        camera motion estimation: 3
        SLAM: 3
        endoscopy: 2
        endoscope: 2
        SOTA: 1

# 通知の閾値
score_threshold: 0
